# Generated by Django 5.1.4 on 2024-12-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='author', max_length=255, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
