# Generated by Django 5.1.4 on 2024-12-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
    ]
