# Generated by Django 5.1.4 on 2024-12-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookG',
        ),
    ]
