# Generated by Django 5.1.4 on 2024-12-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0002_rename_book_bookg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='bookg',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Рецензия', 'verbose_name_plural': 'Рецензии'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='books',
            new_name='book',
        ),
    ]
