# Generated by Django 5.1.4 on 2024-12-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0003_alter_author_options_alter_bookg_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='bookg',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_anonimous',
            field=models.BooleanField(default=False, verbose_name='Анонимно'),
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='Приоритет жанра')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.bookg', verbose_name='Книга')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Связь книга жанр',
                'verbose_name_plural': 'Связb книга жанр',
            },
        ),
        migrations.AddField(
            model_name='bookg',
            name='genres',
            field=models.ManyToManyField(related_name='books', through='gpt4.BookGenre', to='gpt4.genre', verbose_name='Жанры'),
        ),
    ]
