# Generated by Django 5.1.4 on 2024-12-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0005_rename_is_anonimous_review_is_anonymous'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookgenre',
            constraint=models.UniqueConstraint(fields=('book', 'genre'), name='unique_book_genre'),
        ),
    ]
